categories:
  - title: "Security"
    label: security
  - title: "Added"
    label: feature
  - title: "Fixed"
    label: bug
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
no-changes-template: '- No changes'
template: |
  ## Changed

  $CHANGES
